### ISSUE TITLE
Following ctor causes segfault: `FUnknownPtr(const FUnknownPtr &p) : IPtr<I>(p) {}`

### ISSUE THREAD

**Issue by GavinRay97** [Superbelko/ohmygentool#15] opened 2021-05-14 22:45 UTC
I spent a good bit of time reducing this from third-party code to minimum reproduction, and this seems to be it:

https://github.com/steinbergmedia/vst3_pluginterfaces/blob/b8566ef3b2a0cba60a96e3ef2001224c865c8b36/base/funknown.h#L401-L416
https://github.com/steinbergmedia/vst3_pluginterfaces/blob/b8566ef3b2a0cba60a96e3ef2001224c865c8b36/base/smartpointer.h
```cpp
template <class T>
class IPtr {
public:
  int someInt() { return 1; }
};

class FUnknown;

template <class I>
class FUnknownPtr : public IPtr<I> {
public:
  //------------------------------------------------------------------------
  inline FUnknownPtr(FUnknown *unknown);
  inline FUnknownPtr(const FUnknownPtr &p) : IPtr<I>(p) {} // SEGMENTATION FAULT
  inline FUnknownPtr() {}

  inline FUnknownPtr &operator=(const FUnknownPtr &p) {
    IPtr<I>::operator=(p);
    return *this;
  }
  inline I *operator=(FUnknown *unknown);
  inline I *getInterface() { return this->ptr; }
};
```

**Comment by Superbelko** [comment] 2021-05-15 05:43
I'll take care of it myself. Templates requires a lot of extra handling and debugging.

**Comment by Superbelko** [comment] 2021-05-17 06:34
Ok, this one is tricky.
The problem is fixed but I've hit more untranslated code cases when writing tests with reduced example from that VST3 stuff.

I'll push fix for this today and fix the rest later on.

**Closed** 2021-05-17 18:16 UTC

**Comment by GavinRay97** [comment] 2021-05-17 20:27
> Ok, this one is tricky.
> The problem is fixed but I've hit more untranslated code cases when writing tests with reduced example from that VST3 stuff.
> 
> I'll push fix for this today and fix the rest later on.

Thank you!!
